openapi: 3.0.3
info:
  title: Post API
  description: |-
    ì„¤ëª…
servers:
  - url: http://localhost:3000
tags:
  - name: article
    description:
    externalDocs:
      description: Find out more
      url: http://localhost:3000
paths:
  /api/article:
    patch:
      tags:
        - article
      summary: ê²Œì‹œê¸€ ìˆ˜ì •
      description: ê²Œì‹œê¸€ ë‚´ìš©ì„ ìˆ˜ì •í•©ë‹ˆë‹¤
      operationId: updateFreeArticle
      requestBody:
        description: ìˆ˜ì •í•  ê²Œì‹œê¸€ ë‚´ìš©ì´ ë‹´ê²¨ìˆìŠµë‹ˆë‹¤
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  example: "7d0cf64a-2c53-4a0a-b5f2-6209a7ff662f"
                title:
                  type: string
                  example: "aaaaaaaaaaaaaaaağŸ˜ƒaaa"
                content:
                  type: string
                  example: "ğŸ˜ƒğŸ˜ƒğŸ˜ƒğŸ˜ƒğŸ˜ƒ"
                password:
                  type: string
                  example: "asd1sd"

        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: integer
                example: 1

        "500":
          description: Internal Server Error

    post:
      tags:
        - article
      summary: ê²Œì‹œê¸€ ë“±ë¡
      description: ìƒˆë¡œìš´ ê²Œì‹œê¸€ì„ ë“±ë¡í•©ë‹ˆë‹¤
      operationId: postArticleToFreeBoard
      requestBody:
        description:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  example: "7d0cf64a-2c53-4a0a-b5f2-6209a7ff662f"
                title:
                  type: string
                  example: "aaaaaaaaaaaaaaaağŸ˜ƒaaa"
                content:
                  type: string
                  example: "ğŸ˜ƒğŸ˜ƒğŸ˜ƒğŸ˜ƒğŸ˜ƒ"
                password:
                  type: string
                  example: "asd1sd"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  createdAt:
                    type: string
                    example: "2022-09-06T12:12:02.727Z"
                  updateAt:
                    type: string
                    example: "2022-09-06T12:12:02.728Z"
                  articleId:
                    type: string
                    example: "5f04f51b-64de-4200-a2d2-7033de275f7b"
                  sequenceId:
                    type: integer
                    example: 93,
                  userId:
                    type: string
                    example: "7d0cf64a-2c53-4a0a-b5f2-6209a7ff662f"
                  title:
                    type: string
                    example: "aaaaaaaaaaaaaaaağŸ˜ƒaaa"
                  content:
                    type: string
                    example: "ğŸ˜ƒğŸ˜ƒğŸ˜ƒğŸ˜ƒğŸ˜ƒ"
                  password:
                    type: string
                    example: "$2b$05$326IuoERIPNJG5Y8eGhFoOvbUNYFFlwNtbVQxev4wFrISGFaN6aL6"
        "500":
          description: Internal Server Error

    delete:
      tags:
        - freeboard
      summary: ììœ  ê²Œì‹œê¸€ ì‚­ì œ
      description: í•˜ë‚˜ì˜ ììœ  ê²Œì‹œê¸€ì„ ì‚­ì œí•©ë‹ˆë‹¤
      operationId: deleteArticleForFreeBoard
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 2
                    grade:
                      type: integer
                      example: 2
                articleId:
                  type: integer
                  example: 294
      responses:
        "200":
          description: successful operation
        "500":
          description: Internal Server Error
    get:
      tags:
        - freeboard
      summary: ê²Œì‹œê¸€ ì¡°íšŒ
      description: í•˜ë‚˜ì˜ ê²Œì‹œê¸€ì„ ì¡°íšŒí•©ë‹ˆë‹¤
      operationId: getArticleForFreeBoard
      parameters:
        - name: articleId
          in: query
          description: ê²Œì‹œê¸€ ì•„ì´ë””
          required: true
          explode: true
          schema:
            type: integer
            example: 193
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                    example: 2
                  title:
                    type: string
                    example: "ì²«ë²ˆì§¸ ê²Œì‹œê¸€ ë“±ë¡ ì…ë‹ˆë‹¤"
                  content:
                    type: string
                    example: "ê²Œì‹œê¸€ ë“±ë¡ í•˜ì˜€ìŠµë‹ˆë‹¤"
                  createdAt:
                    type: string
                    format: date-time
                    example: "2022-09-05 05:54:53"
                  updatedAt:
                    type: string
                    format: date-time
                    example: "2022-09-05 05:54:53"
        "500":
          description: Internal Server Error
